### ISSUE TITLE
Thank You Note

### ISSUE THREAD

**Issue by O957** [david-vanderhaar/histomap#12]
Dear @david-vanderhaar,

(1) Thank you very much for creating `histomap`.
(2) I am interested in pursuing further avenues for visualization of cliodynamics / historical dynamics related work.
(3) I may use this repository as a template for similar visualizations, in this regard, if this is okay.
(4) Best wishes to you with further visualizations you make related to cliodynamics / historical dynamics.
(5) Again, thank you, and may this repository live a long and useful life!

_This issue may be closed as completed once read._

**Comment by david-vanderhaar** [comment]
Thank you for the note. I'm happy to hear that. Feel free to use it as you like. I often consider updating it since the version of some of the js libraries are out of date. I am also interested in adding some features for fun.
